---
provider: openstack
cloud_service_group: Storage
cloud_service_type: Storage
name: Count by Backend
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.volume_backend_name
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT