---
provider: openstack
cloud_service_group: Storage
cloud_service_type: Storage
name: Total Allocated Volume Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.total_allocated_volume_size
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: GB
