---
provider: openstack
cloud_service_group: Storage
cloud_service_type: Storage
name: Total Volume Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.total_volume_count
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0