---
provider: openstack
cloud_service_group: Compute
cloud_service_type: Image
name: Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.size_mb
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: MB