---
provider: openstack
cloud_service_group: Storage
cloud_service_type: Share
name: Total Size(GiB)
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.size_gb
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0