---
provider: openstack
cloud_service_group: Compute
cloud_service_type: Hypervisor
name: Total Memory(GiB)
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.memory_size
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0