---
provider: openstack
cloud_service_group: Compute
cloud_service_type: Hypervisor
name: Used Memory
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.memory_used
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: MB