---
provider: openstack
cloud_service_group: Compute
cloud_service_type: Instance
name: Count by Project
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.project_name
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT