---
provider: openstack
cloud_service_group: Storage
cloud_service_type: Volume
name: Count by Type
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.volume_type
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT