---
provider: openstack
cloud_service_group: Storage
cloud_service_type: Volume
name: Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.size_gb
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: GB